/**
 * Score the fixture corpus across all 24 axes with the model.
 *
 *   npx tsx scripts/corpus/score-fixtures.ts
 *
 * WHY THIS EXISTS
 * components/mock/fixtures.ts was hand-written, and each dish only sets about
 * seven of the twenty four axes. Every other axis is exactly 0.
 *
 * That is not a cosmetic gap, it is why the quiz kept telling everyone they
 * were an "acid person". fitTheta regresses on (phi_winner - phi_loser), so an
 * axis that is 0 on every dish produces a zero difference on every duel and can
 * never move off the prior. Only the handful of axes that WERE populated could
 * ever move, so the same few traits surfaced no matter what anyone picked, and
 * the profile was decided by which axes someone bothered to fill in by hand
 * rather than by what the person chose.
 *
 * This runs the real extraction prompt (scripts/corpus/extract.ts, the same one
 * the live corpus pipeline uses) over every fixture dish and writes a dense,
 * per-axis, per-dish vector with honest per-axis confidence.
 *
 * OUTPUT
 * Writes lib/store/dish-vectors.generated.ts. The fixtures stay untouched:
 * they are Track B's file, and the generated vectors are layered over them by
 * lib/store/corpus.ts, so a regeneration is a data change and never a hand
 * edit to somebody else's component file.
 */

import { config as loadEnv } from 'dotenv';
loadEnv({ path: '.env.local' });

import { writeFileSync } from 'node:fs';
import { AXIS_COUNT } from '../../contracts/axes';
import { DISHES, VENUES } from '../../components/mock/fixtures';
import { extractBatch, type MenuItem } from './extract';
import { hasModelCredentials } from '../../core/anthropic-client';

const OUT = 'lib/store/dish-vectors.generated.ts';

function venueOf(venueId: string) {
  return VENUES.find((v) => v.id === venueId);
}

async function main(): Promise<void> {
  if (!hasModelCredentials()) {
    console.error('No ANTHROPIC_API_KEY in .env.local. Nothing to score.');
    process.exit(1);
  }

  const items: MenuItem[] = DISHES.map((d) => {
    const v = venueOf(d.venueId);
    return {
      key: d.id,
      venueKey: d.venueId,
      name: d.name,
      description: d.description,
      priceCents: d.priceCents,
      // The venue name carries real cuisine signal ("Taqueria", "Kopitiam"),
      // which is exactly the context the extractor needs to judge a dish it
      // has only one line of description for.
      venueCuisine: v ? `${v.name}, ${v.neighborhood}` : null,
    };
  });

  console.log(`\nscoring ${items.length} dishes across ${AXIS_COUNT} axes\n`);

  // One batch: twenty dishes is well inside a single request, and keeping it
  // in one call means the model scores them RELATIVE to each other, which is
  // what makes the resulting numbers comparable.
  const results = await extractBatch(items);

  const byKey = new Map(results.map((r) => [r.key, r]));
  const lines: string[] = [];

  for (const d of DISHES) {
    const r = byKey.get(d.id);
    if (!r) {
      console.warn(`  no result for ${d.id} (${d.name})`);
      continue;
    }
    const confident = AXIS_COUNT - r.maskedAxes.length;
    console.log(`  ${d.id.padEnd(4)} ${d.name.slice(0, 30).padEnd(32)} ${confident}/24 axes`);
    lines.push(
      `  ${JSON.stringify(d.id)}: {\n` +
        `    phi: [${r.phi.map((n) => n.toFixed(2)).join(', ')}],\n` +
        `    confidence: [${r.confidence.map((n) => n.toFixed(2)).join(', ')}],\n` +
        `  },`,
    );
  }

  const file = `/**
 * GENERATED by scripts/corpus/score-fixtures.ts. Do not hand edit.
 *
 * Dense per-axis vectors for the fixture corpus, scored by the same extraction
 * prompt the live pipeline uses. Replaces the hand-written sparse vectors in
 * components/mock/fixtures.ts, where most axes were 0 and therefore could never
 * move a fitted profile.
 */

export interface GeneratedDishVector {
  phi: number[];
  confidence: number[];
}

export const GENERATED_VECTORS: Record<string, GeneratedDishVector> = {
${lines.join('\n')}
};
`;

  writeFileSync(OUT, file);
  const meanConfident =
    results.reduce((s, r) => s + (AXIS_COUNT - r.maskedAxes.length), 0) / results.length;
  console.log(`\nwrote ${OUT}`);
  console.log(`mean confident axes per dish: ${meanConfident.toFixed(1)} (was ~7 hand written)\n`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
